services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami/kafka


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled= false

    ports:
      - "9200:9200"  # Elasticsearch listens on HTTP port 9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.1
    ports:
      - "5601:5601"  # Kibana UI
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"  # Kibana connects over HTTP
      xpack.security.enabled: false

    depends_on:
      - elasticsearch

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - kafka
      - elasticsearch

volumes:
  zookeeper_data:
  zookeeper_datalog:
  kafka_data:
  elasticsearch_data:
