# services:
#   zookeeper:
#     image: wurstmeister/zookeeper
#     ports:
#       - "2181:2181"

#   kafka:
#     image: bitnami/kafka:latest
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_BROKER_ID: 1
#       ALLOW_PLAINTEXT_LISTENER: "yes"
    
#   mongo:
#     image: mongo:latest
#     ports:
#       - "27017:27017"

#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
#     environment:
#       - discovery.type=single-node
#     ports:
#       - "9200:9200"

#   webapp:
#     build: .
#     ports:
#       - "4000:80"
#     depends_on:
#       - kafka
#       - mongo
#       - elasticsearch
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
